site_name: Alppi Documentation



nav:
  - Home: index.md
  - API: 
    - api/index.md
    - Authentication:
      - api\authentication\index.md
      - Login:
        - api/authentication/login/login.md
    - System: 
      - api/system/index.md
  - Release Notes:
    - Releases: # COLOCAR SEMPRE DECRESCENTE
      - Version 1.0.0:
        - release-notes/v1/v1.0.1.md 
        - release-notes/v1/v1.0.0.md

      - Version 2.0.0:
        - release-notes/v2/v2.0.1.md 
        - release-notes/v2/v2.0.0.md



theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.path
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/square-github
    admonition:
      note: octicons/pencil-16
      abstract: octicons/multi-select-16
      info: octicons/info-16
      tip: octicons/rocket-16
      success: octicons/check-circle-16
      question: octicons/question-16
      warning: octicons/stop-16
      failure: octicons/x-circle-16
      danger: octicons/alert-16
      bug: octicons/bug-16
      example: octicons/list-unordered-16
      quote: octicons/comment-16


plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/mkdocsoad.css
  - css/crud.css


# Copyright
copyright: Copyright &copy; 2024 - 2024 Alppi Technology